In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [4]:
np.array( [1,3,4,5] )

array([1, 3, 4, 5])

In [5]:
arr = np.array( [1,3,4,5] )
arr

array([1, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.dtype

dtype('int32')

In [8]:
arr = np.array( [1,3,4,5.5] )
arr

array([1. , 3. , 4. , 5.5])

In [9]:
arr.dtype

dtype('float64')

In [10]:
arr[1]

3.0

In [11]:
arr[-1]

5.5

In [12]:
arr.shape

(4,)

In [13]:
arr = np.array( [1,3,4,5] )
arr

array([1, 3, 4, 5])

In [14]:
arr = np.array( [1,3,4,5, 2+3j] )
print(arr)
print(arr.shape)
print(arr.dtype)

[1.+0.j 3.+0.j 4.+0.j 5.+0.j 2.+3.j]
(5,)
complex128


In [15]:
arr = np.array( [1,3.5,4,5, 2+3j] )
print(arr)
print(arr.shape)
print(arr.dtype)

[1. +0.j 3.5+0.j 4. +0.j 5. +0.j 2. +3.j]
(5,)
complex128


In [16]:
arr = np.array( [1,3,4.5,5, 2+3j, True] )
print(arr)
print(arr.shape)
print(arr.dtype)

[1. +0.j 3. +0.j 4.5+0.j 5. +0.j 2. +3.j 1. +0.j]
(6,)
complex128


In [17]:
arr = np.array( [1,3,4.5,5, 2+3j, False] )
print(arr)
print(arr.shape)
print(arr.dtype)

[1. +0.j 3. +0.j 4.5+0.j 5. +0.j 2. +3.j 0. +0.j]
(6,)
complex128


In [18]:
arr = np.array( [1,3,4.5,5, 2+3j, True, "Darshan"] )
print(arr)
print(arr.shape)
print(arr.dtype)

['1' '3' '4.5' '5' '(2+3j)' 'True' 'Darshan']
(7,)
<U64


In [19]:
arr = np.array( [1,3,4,5] )
print(arr)

[1 3 4 5]


In [20]:
np.sum(arr)

13

In [21]:
np.max(arr)

5

In [22]:
np.mean(arr)

3.25

In [23]:
np.std(arr)

1.479019945774904

In [24]:
arr = np.array( [1,3,4.5,5, 2+3j, True, "Darshan"] )
print(arr)
print(arr.shape)
print(arr.dtype)

['1' '3' '4.5' '5' '(2+3j)' 'True' 'Darshan']
(7,)
<U64


In [25]:
np.sum(arr)

TypeError: cannot perform reduce with flexible type

In [27]:
# 2D
arr = np.array( [ [1,2,3] , [4,5,6] , [8,9,7] ] )
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 7]])

In [28]:
arr[0]

array([1, 2, 3])

In [29]:
arr[2][1]

9

In [30]:
arr.shape

(3, 3)

In [31]:
# 2D
arr = np.array( [ [1,2,3] , [4,5,6] , [8] ] )
arr

array([list([1, 2, 3]), list([4, 5, 6]), list([8])], dtype=object)

In [32]:
arr.shape

(3,)

In [33]:
# 2D
arr = np.array( [ [1,2,3] , [4,5,6] , [8,None, None] ] )
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, None, None]], dtype=object)

In [34]:
arr.shape

(3, 3)

In [35]:
np.zeros( (2,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.zeros( (4,5) )

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.zeros( (2,4) ).dtype

dtype('float64')

In [38]:
np.ones( (2,4) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
np.ones( (5,4) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.twos( (2,4) )

AttributeError: module 'numpy' has no attribute 'twos'

In [42]:
np.identity( 4 )

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
arr = np.random.randn(3,4)
arr

array([[ 0.75337241,  0.66302584,  0.69497637,  0.08891782],
       [ 1.97396119,  0.45878827,  0.33514554,  1.67386505],
       [ 1.87100274,  0.79356136, -0.3914078 ,  0.70938823]])

In [45]:
arr = np.random.randn(10,5)
arr

array([[ 0.1892905 , -0.72416032, -0.08232886,  0.77402832, -0.81211618],
       [-0.70829365, -1.03798351,  0.69268848,  0.46765448, -0.0191708 ],
       [-0.64689929,  1.00840592,  1.25293984,  0.22073938,  0.32306292],
       [ 0.77342437,  0.27581516,  1.01884499, -1.33315589,  0.12703242],
       [-0.07919051, -0.33751613,  0.70944826, -1.94486358,  0.18463987],
       [ 0.0135557 , -0.28249967,  0.47498621,  0.56923916, -0.39620547],
       [-0.84405495,  1.48799478, -0.82395183, -0.21044163,  0.17447627],
       [ 0.58337582, -0.47413071, -0.27374891, -1.3603268 , -0.51295911],
       [-0.68760637, -0.19773909,  0.19386063,  0.12043141, -0.37090699],
       [ 1.43844213, -0.7951711 ,  0.09296674,  2.04233869, -0.66695442]])

In [46]:
print(np.max(arr),np.min(arr))

2.042338687927478 -1.9448635823167364


In [47]:
from numpy import array
data = array([1,2,3,4,5])
print(data)
print(type(data))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [48]:
from numpy import array
data = array([ [1,2],[3,4] ])
print(data)
print(type(data))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


Indexing and Slicing

In [49]:
# 2D
arr = np.array( [ [1,2,3] , [4,5,6] , [8,9,7] ] )
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 7]])

In [50]:
arr.shape

(3, 3)

In [51]:
arr[1]

array([4, 5, 6])

In [52]:
arr[1][0]

4

In [53]:
arr[1][1]

5

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 7]])

In [55]:
arr[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 7]])

In [56]:
arr[0:1]

array([[1, 2, 3]])

In [57]:
arr[ : , 2 ]

array([3, 6, 7])

In [59]:
arr[ 1 , : ]

array([4, 5, 6])

In [60]:
arr[ 1 ]

array([4, 5, 6])

In [61]:
range(5)

range(0, 5)

In [62]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [63]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [68]:
np.arange(12).reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [69]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [71]:
np.arange(12).reshape(4,1,3)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [79]:
np.arange(12).reshape(1,1,12)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]])

In [80]:
np.arange(12).reshape(1,1,12).dtype

dtype('int32')

In [81]:
np.arange(12).reshape(1,1,12).shape

(1, 1, 12)

In [73]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [74]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [75]:
arr[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
arr[0][0]

array([0, 1, 2])

In [77]:
arr[0][1]

array([3, 4, 5])

In [78]:
arr[1][1][1]

10

In [83]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr[10:]

array([], dtype=int32)

In [86]:
arr[5:8]

array([5, 6, 7])

In [87]:
arr[ : -5 ]

array([0, 1, 2, 3, 4])

In [88]:
arr[ -4 :  ]

array([6, 7, 8, 9])

In [89]:
arr[ 1 : -4 ]

array([1, 2, 3, 4, 5])

In [94]:
# Very Important for ML

arr = np.array([ [11,22,33],[44,55,66],[77,88,99] ])
print(arr)
print()

X = arr[ : , :-1 ]
print(X)
print()

y = arr[ : , -1 ]
print(y)

[[11 22 33]
 [44 55 66]
 [77 88 99]]

[[11 22]
 [44 55]
 [77 88]]

[33 66 99]


Boolean Indexing

In [95]:
cities = np.array(["delhi","bangalore","mumbai","chennai","bhopal"])
cities

array(['delhi', 'bangalore', 'mumbai', 'chennai', 'bhopal'], dtype='<U9')

In [96]:
city_data = np.random.randn(5,3)
city_data

array([[-1.15625278, -0.28316719,  0.13611797],
       [ 0.53559666, -1.13366576, -1.05822537],
       [-0.73799442,  0.92533717,  1.54812752],
       [-1.7883214 , -1.53803203, -0.63181484],
       [-0.01126725,  0.99005564,  0.02134642]])

In [97]:
cities == "mumbai"

array([False, False,  True, False, False])

In [98]:
city_data[cities == "mumbai"]

array([[-0.73799442,  0.92533717,  1.54812752]])

In [99]:
city_data[cities == "mumbra"]

array([], shape=(0, 3), dtype=float64)

In [100]:
city_data

array([[-1.15625278, -0.28316719,  0.13611797],
       [ 0.53559666, -1.13366576, -1.05822537],
       [-0.73799442,  0.92533717,  1.54812752],
       [-1.7883214 , -1.53803203, -0.63181484],
       [-0.01126725,  0.99005564,  0.02134642]])

In [101]:
city_data > 0

array([[False, False,  True],
       [ True, False, False],
       [False,  True,  True],
       [False, False, False],
       [False,  True,  True]])

In [102]:
city_data[ city_data > 0 ]

array([0.13611797, 0.53559666, 0.92533717, 1.54812752, 0.99005564,
       0.02134642])

In [103]:
city_data

array([[-1.15625278, -0.28316719,  0.13611797],
       [ 0.53559666, -1.13366576, -1.05822537],
       [-0.73799442,  0.92533717,  1.54812752],
       [-1.7883214 , -1.53803203, -0.63181484],
       [-0.01126725,  0.99005564,  0.02134642]])

In [105]:
city_data[ city_data > 0 ] = 0

In [106]:
city_data

array([[-1.15625278, -0.28316719,  0.        ],
       [ 0.        , -1.13366576, -1.05822537],
       [-0.73799442,  0.        ,  0.        ],
       [-1.7883214 , -1.53803203, -0.63181484],
       [-0.01126725,  0.        ,  0.        ]])

In [107]:
city_data[ city_data < 0 ] = 9999
city_data

array([[9999., 9999.,    0.],
       [   0., 9999., 9999.],
       [9999.,    0.,    0.],
       [9999., 9999., 9999.],
       [9999.,    0.,    0.]])

Ufuns

Universal Functions

In [109]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [110]:
arr + 5
# Broadcasting

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [111]:
arr * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [112]:
arr1 = np.arange(15).reshape(5,3)

arr2 = np.arange(5).reshape(5,1)

arr2 + arr1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [114]:
#  Mat Mult

A = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
B = np.array([ [1,2,3],[4,5,6],[3,6,1] ])
print(A)
print()
print(B)
print()

A.dot(B) # simple array multiplication

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [3 6 1]]



array([[ 18,  30,  18],
       [ 42,  69,  48],
       [ 66, 108,  78]])

In [115]:
#  Transpose

A = np.arange(15).reshape(3,5)
print(A)
print()

A.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]



array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [117]:
a = np.array([ [7,5,-3],[3,-5,2],[5,3,-7] ])
b = np.array([16,-8,0])

np.linalg.solve(a,b)

array([1., 3., 2.])

In [118]:
a = np.array([ [7,5,-3],[3,-5,2],[5,3,-7] ])
print(a)

np.linalg.inv(a)

[[ 7  5 -3]
 [ 3 -5  2]
 [ 5  3 -7]]


array([[ 0.11328125,  0.1015625 , -0.01953125],
       [ 0.12109375, -0.1328125 , -0.08984375],
       [ 0.1328125 ,  0.015625  , -0.1953125 ]])

In [119]:
a = np.array([ [7,5,-3],[3,-5,2],[5,3,-7] ])
print(a)

np.linalg.det(a)

[[ 7  5 -3]
 [ 3 -5  2]
 [ 5  3 -7]]


255.99999999999994

In [120]:
# Broadcasting

a = np.array([0,1,2])
b = np.array([5,5,5])
a+b

array([5, 6, 7])

In [122]:
a+7

array([7, 8, 9])

In [125]:
# IMP for ML
a = np.arange(3)
b = np.arange(3)[ : , np.newaxis ]

print(a)
print(a.shape)

print()
print(b)
print(b.shape)

[0 1 2]
(3,)

[[0]
 [1]
 [2]]
(3, 1)


In [126]:
# IMP for ML
a = np.arange(3)
b = np.arange(3).reshape(-1,1)

print(a)
print(a.shape)

print()
print(b)
print(b.shape)

[0 1 2]
(3,)

[[0]
 [1]
 [2]]
(3, 1)


In [127]:
# Structured Arrays

name = ['Alice','Bob','Cathy','Douglas']
age = [25,45,37,19]
weight = [55.0,85.5,68.0,61.5]

In [133]:
data = np.zeros(4, dtype={ 'names' : ('name','age','weight'),
                            'formats':('U10','i4','f8')})
print(data)
print(data.dtype)

[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [134]:
data['name'] = name
data['age'] = age
data['weight'] = weight

print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Douglas', 19, 61.5)]


In [135]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Douglas'], dtype='<U10')

In [136]:
data[0]

('Alice', 25, 55.)

In [138]:
# Get the name from the last row
data[-1]['name']

'Douglas'

In [143]:
# Get names where the age is under 30
data[data['age'] < 30]['name']

array(['Alice', 'Douglas'], dtype='<U10')

In [147]:
# get the names and ages where weight is greater than 65
data[data['weight'] > 65][['name','age']]

array([('Bob', 45), ('Cathy', 37)],
      dtype={'names':['name','age'], 'formats':['<U10','<i4'], 'offsets':[0,40], 'itemsize':52})